export const anims = [
  {
    animLabel: "moveSouth",
    frameStart: 0,
    frameEnd: 7,
    playerTypes: ["rifle", "barbedBat"],
    frameRate: 12,
  },
  {
    animLabel: "moveEast",
    frameStart: 12,
    frameEnd: 19,
    playerTypes: ["rifle", "barbedBat"],
    frameRate: 12,
  },
  {
    animLabel: "moveNorth",
    frameStart: 23,
    frameEnd: 30,
    playerTypes: ["rifle", "barbedBat"],
    frameRate: 12,
  },
  {
    animLabel: "moveWest",
    frameStart: 33,
    frameEnd: 40,
    playerTypes: ["rifle", "barbedBat"],
    frameRate: 12,
  },
  {
    animLabel: "attackSouth",
    frameStart: 8,
    frameEnd: 10,
    playerTypes: ["rifle", "barbedBat"],
    frameRate: 12,
  },
  {
    animLabel: "attackEast",
    frameStart: 20,
    frameEnd: 23,
    playerTypes: ["rifle", "barbedBat"],
    frameRate: 12,
  },
  {
    animLabel: "attackNorth",
    frameStart: 30,
    frameEnd: 33,
    playerTypes: ["rifle", "barbedBat"],
    frameRate: 12,
  },
  {
    animLabel: "attackWest",
    frameStart: 40,
    frameEnd: 43,
    playerTypes: ["rifle", "barbedBat"],
    frameRate: 12,
  },
];
